name: UpToDateneuroencoders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - scikit-learn
      - scipy
      - seaborn
      - tqdm
      - tables
      - jupyter
      - pydot
      - pydotplus
      - graphviz
      - pykeops
      - pytorch
      - pre-commit
